const enemyData = {
  enemy1 : {
    speed : 5,
    health : 1,
    bulletPower : 1,
    bulletSpeed : 8,
    energy: 2,
    width : 50,
    bg : './images/enemies/enemy1.png',
    energyCont : './images/dropItem1.png',
    bulletBg : './images/enemies/bullet1.png',
    bulletWidth: '8px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy2 : {
    speed : 5,
    health : 4,
    bulletPower : 2,
    bulletSpeed : 10,
    energy: 4,
    width : 50,
    bg : './images/enemies/enemy2.png',
    energyCont : './images/dropItem2.png',
    bulletBg : './images/enemies/bullet2.png',
    bulletWidth: '8px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy3 : {
    speed : 6,
    health : 5,
    bulletPower : 2,
    bulletSpeed : 12,
    energy: 6,
    width : 50,
    bg : './images/enemies/enemy3.png',
    energyCont : './images/dropItem3.png',
    bulletBg : './images/enemies/bullet3.png',
    bulletWidth: '8px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy4 : {
    speed : 7,
    health : 7,
    bulletPower : 3,
    bulletSpeed : 15,
    energy: 8,
    width : 60,
    bg : './images/enemies/enemy4.png',
    energyCont : './images/dropItem4.png',
    bulletBg : './images/enemies/bullet4.png',
    bulletWidth: '25px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy5 : {
    speed : 7,
    health : 8,
    bulletPower : 4,
    bulletSpeed : 16,
    energy: 10,
    width : 60,
    bg : './images/enemies/enemy5.png',
    energyCont : './images/dropItem5.png',
    bulletBg : './images/enemies/bullet5.png',
    bulletWidth: '25px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy6 : {
    speed : 8,
    health : 10,
    bulletPower : 5,
    bulletSpeed : 17,
    energy: 12,
    width : 60,
    bg : './images/enemies/enemy6.png',
    energyCont : './images/dropItem6.png',
    bulletBg : './images/enemies/bullet6.png',
    bulletWidth: '25px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy7 : {
    speed : 9,
    health : 12,
    bulletPower : 6,
    bulletSpeed : 18,
    energy: 14,
    width : 60,
    bg : './images/enemies/enemy7.png',
    energyCont : './images/dropItem7.png',
    bulletBg : './images/enemies/bullet7.png',
    bulletWidth: '25px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy8 : {
    speed : 10,
    health : 14,
    bulletPower : 7,
    bulletSpeed : 18,
    energy: 16,
    width : 60,
    bg : './images/enemies/enemy8.png',
    energyCont : './images/dropItem8.png',
    bulletBg : './images/enemies/bullet8.png',
    bulletWidth: '25px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy9 : {
    speed : 12,
    health : 15,
    bulletPower : 9,
    bulletSpeed : 19,
    energy: 18,
    width : 60,
    bg : './images/enemies/enemy9.png',
    energyCont : './images/dropItem9.png',
    bulletBg : './images/enemies/bullet9.png',
    bulletWidth: '25px',
    bulletHeight: '25px',
    fireInterval : 100,
  },
  enemy10 : {
    speed : 12,
    health : 100,
    bulletPower : 15,
    bulletSpeed : 20,
    energy: 50,
    width : 100,
    bg : './images/enemies/enemy10.png',
    energyCont : './images/dropItem10.png',
    bulletBg : './images/enemies/bullet10.png',
    bulletWidth: '50px',
    bulletHeight: '100px',
    fireInterval : 100,
  },
}
