const heroData = {
  hero1 : {
    width : 50,
    bg : './images/flight1.png',
    bulletBg : './images/bullet1.png',
    bulletWidth: 10,
    bulletHeight: 25,
  },
  hero2 : {
    width : 50,
    bg : './images/flight2.png',
    bulletBg : './images/bullet2.png',
    bulletWidth: 25,
    bulletHeight:25,
  },
  hero3 : {
    width : 50,
    bg : './images/flight3.png',
    bulletBg : './images/bullet3.png',
    bulletWidth: 20,
    bulletHeight: 35,
  },
  hero4 : {
    width : 50,
    bg : './images/flight4.png',
    bulletBg : './images/bullet4.png',
    bulletWidth: 20,
    bulletHeight: 33,
  },
  hero5 : {
    width : 50,
    bg : './images/flight5.png',
    bulletBg : './images/bullet5.png',
    bulletWidth: 20,
    bulletHeight: 43,
  },
  hero6 : {
    width : 50,
    bg : './images/flight6.png',
    bulletBg : './images/bullet6.png',
    bulletWidth: 20,
    bulletHeight: 62,
  },
  hero7 : {
    width : 50,
    bg : './images/flight7.png',
    bulletBg : './images/bullet7.png',
    bulletWidth: 22,
    bulletHeight: 48,
  },
  hero8 : {
    width : 50,
    bg : './images/flight8.png',
    bulletBg : './images/bullet8.png',
    bulletWidth: 20,
    bulletHeight: 66,
  },
  hero9 : {
    width : 50,
    bg : './images/flight9.png',
    bulletBg : './images/bullet9.png',
    bulletWidth: 30,
    bulletHeight: 71,
  },
  hero10 : {
    width : 50,
    bg : './images/flight10.png',
    bulletBg : './images/bullet10.png',
    bulletWidth: 20,
    bulletHeight: 64,
  },
  hero11 : {
    width : 50,
    bg : './images/flight11.png',
    bulletBg : './images/bullet11.png',
    bulletWidth: 30,
    bulletHeight: 35,
  },
  hero12 : {
    width : 50,
    bg : './images/flight12.png',
    bulletBg : './images/bullet12.png',
    bulletWidth: 20,
    bulletHeight: 39,
  },
  hero13 : {
    width : 50,
    bg : './images/flight13.png',
    bulletBg : './images/bullet13.png',
    bulletWidth: 30,
    bulletHeight: 30,
  },

}
